version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:14.15.4
    steps:
      - checkout
      - run: yarn install
      - run: yarn test:coverage
      - store_artifacts:
          path: coverage

workflows:
  test:
    jobs:
      - build
