version: 2.1

jobs:
  build:
    docker:
      - image: bash:5.0.7
    resource_class: gpu.nvidia.medium
    steps:
      - checkout
      - run: ./main.sh

workflows:
  test:
    jobs:
      - build
