version: 2.1

orbs:
  slack: circleci/slack@4.4.2

jobs:
  build:
    docker:
      - image: cimg/base:2021.07-20.04
    steps:
      - checkout
      - run: ./main.sh
      - slack/notify

workflows:
  test:
    jobs:
      - build:
          context: slack-bot-token
