version: 2.1

jobs:
  build:
    docker:
      - image: bash:5.0.7
    steps:
      - checkout
      - run: ./main.sh

workflows:
  test:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - another-tag
            tags:
              only:
                - tag-11-17

