version: 2.1

jobs:
  build:
    docker:
      - image: bash:5.0.7
    steps:
      - checkout
      - run: ./main.sh

workflows:
  test:
    jobs:
      - my-approval-job:
          type: approval
      - build:
          requires:
            - my-approval-job
