version: 2.1

jobs:
  build:
    docker:
      - image: bash:5.0.7
    steps:
      - checkout
      - run: ./main.sh

workflows:
  test1: { jobs: [build] }
  test2: { jobs: [build] }
  test3: { jobs: [build] }
  test4: { jobs: [build] }
  test5: { jobs: [build] }
  test6: { jobs: [build] }
  test7: { jobs: [build] }
  test8: { jobs: [build] }
  test9: { jobs: [build] }
  test10: { jobs: [build] }
  test11: { jobs: [build] }
  test12: { jobs: [build] }
  test13: { jobs: [build] }
  test14: { jobs: [build] }
  test15: { jobs: [build] }
  test16: { jobs: [build] }
  test17: { jobs: [build] }
  test18: { jobs: [build] }
  test19: { jobs: [build] }
  test20: { jobs: [build] }
  test21: { jobs: [build] }
  test22: { jobs: [build] }
  test23: { jobs: [build] }
  test24: { jobs: [build] }
  test25: { jobs: [build] }
  test26: { jobs: [build] }
  test27: { jobs: [build] }
  test28: { jobs: [build] }
  test29: { jobs: [build] }
  test30: { jobs: [build] }
  test31: { jobs: [build] }
  test32: { jobs: [build] }
  test33: { jobs: [build] }
  test34: { jobs: [build] }
  test35: { jobs: [build] }
  test36: { jobs: [build] }
  test37: { jobs: [build] }
  test38: { jobs: [build] }
  test39: { jobs: [build] }
  test40: { jobs: [build] }
  test41: { jobs: [build] }
  test42: { jobs: [build] }
  test43: { jobs: [build] }
  test44: { jobs: [build] }
  test45: { jobs: [build] }
  test46: { jobs: [build] }
  test47: { jobs: [build] }
  test48: { jobs: [build] }
  test49: { jobs: [build] }
  test50: { jobs: [build] }
  test51: { jobs: [build] }
  test52: { jobs: [build] }
  test53: { jobs: [build] }
  test54: { jobs: [build] }
  test55: { jobs: [build] }
  test56: { jobs: [build] }
  test57: { jobs: [build] }
  test58: { jobs: [build] }
  test59: { jobs: [build] }
  test60: { jobs: [build] }
  test61: { jobs: [build] }
  test62: { jobs: [build] }
  test63: { jobs: [build] }
  test64: { jobs: [build] }
  test65: { jobs: [build] }
  test66: { jobs: [build] }
  test67: { jobs: [build] }
  test68: { jobs: [build] }
  test69: { jobs: [build] }
  test70: { jobs: [build] }
  test71: { jobs: [build] }
  test72: { jobs: [build] }
  test73: { jobs: [build] }
  test74: { jobs: [build] }
  test75: { jobs: [build] }
  test76: { jobs: [build] }
  test77: { jobs: [build] }
  test78: { jobs: [build] }
  test79: { jobs: [build] }
  test80: { jobs: [build] }
  test81: { jobs: [build] }
  test82: { jobs: [build] }
  test83: { jobs: [build] }
  test84: { jobs: [build] }
  test85: { jobs: [build] }
  test86: { jobs: [build] }
  test87: { jobs: [build] }
  test88: { jobs: [build] }
  test89: { jobs: [build] }
  test90: { jobs: [build] }
  test91: { jobs: [build] }
  test92: { jobs: [build] }
  test93: { jobs: [build] }
  test94: { jobs: [build] }
  test95: { jobs: [build] }
  test96: { jobs: [build] }
  test97: { jobs: [build] }
  test98: { jobs: [build] }
  test99: { jobs: [build] }
  test100: { jobs: [build] }
