version: 2.1

jobs:
  build:
    docker:
      - image: bash:5.0.7
    steps:
      - checkout
      - run: ./main.sh
  other:
    docker:
      - image: bash:5.0.7
    steps:
      - checkout
      - run: ./main.sh

