version: 2.1

jobs:
  build:
    docker:
      - image: bash:5.0.7
    steps:
      - checkout
      - run: ./main.sh

workflows:
  test:
    jobs:
      - build:
          filter:
            branches:
              ignore:
                - try-adding-a-tag
            tags:
              only:
                - my-new-tag
                


